### ISSUE TITLE
Countdown displays as NaN in IE7 & IE8, but fine in every other browser

### ISSUE THREAD

**Issue by peiledoir** [suryart/spree_active_sale#28]
Hi Suryart,

We have your countdown working great on all browsers except IE7 & IE8, which display each of the countdown numbers as NaN. Any thoughts?

Cheers,
Peiledoir

**Comment by suryart** [comment]
@peiledoir 

spree_active_sale extension uses http://keith-wood.name/countdown.html jquery plugin for countdowns to display on browser. Please check if the plugin works on IE7 and IE8? If not then it maybe because of the HTML5 data attribute which fetches the date of a sale event and then push the date to start the countdown timer, the code is here: https://github.com/suryart/spree_active_sale/blob/master/vendor/assets/javascripts/spree_active_sale/event_timer.js#L1-L21

Let me know if you get any issues?

**Comment by peiledoir** [comment]
Thanks..

So, I tested the http://keith-wood.name/countdown.html jquery plugin within the spree app and it works fine, so its looking like its to do with the data attributes. 

I've read that _"We shouldn’t use data attributes for anything which already has an already established or more appropriate attribute."_ ie Time
http://webdesign.tutsplus.com/tutorials/htmlcss-tutorials/all-you-need-to-know-about-the-html5-data-attribute/

Wondering if this is the issue? Everything I am testing out so far is not working. Have you or anyone else got this work in the Spree rails app on IE8 or IE7?

**Comment by suryart** [comment]
@peiledoir, This is a very nice find. I didn't know about all that. Much appreciated.

However, I think I didn't try this on IE8 or IE7. Will do this as first thing tomorrow. Also, if you can find out the issue( if it is related with jqeury written in event_timer.js) and, send a PR with the fix, I'll be happy to merge a PR.

**Comment by peiledoir** [comment]
Ok, found the issue.

The time format needs to be changed slightly so that IE7&8 can read it properly. 

Originally you had:
**2013-08-06 T00:00:00** (%Y-%m-%dT%H:%M:%S)

But it needs to read:
**2013/08/06 00:00:00** (%Y/%m/%d %H:%M:%S)

Thanks for the awesome plugin!

**Comment by suryart** [comment]
Here is the code which has time formatted that way: https://github.com/suryart/spree_active_sale/blob/master/app/helpers/spree/active_sale_events_helper.rb#L7

So, you can change it with a decorator, or make a permanent fix and send PR.

You're most welcome. I'm glad you liked it. :)
