### ISSUE TITLE
Is there a default layout?

### ISSUE THREAD

**Issue by dfischer** [suryart/spree_active_sale#9]
Is there a default layout that shows this functionality off vs the default spree?

**Comment by suryart** [comment]
Sorry, I didn't get your question. Can you please describe a little bit more about what you mean by default layout?

**Comment by dfischer** [comment]
When you install spree, you get that default layout that shows many products on the homepage and then sidebar.

spree_active_sale aims to show one product with a timer, potentially others in a sidebar as "alternative" sale items. Do we have a layout already in place to show it this way? Or do we depend on the user to modify existing one with helpers that spree_active_sale provides? (harder)

**Comment by suryart** [comment]
No, we do not depend and do not expect user to modify the existing default layout which comes from spree for work with this plugin. I have added home_controller to process live and active sales, which were added by Admin from the Admin area of Active Sales and Active Sale Events. You can have a look at it here: https://github.com/suryart/spree_active_sale/blob/master/app/controllers/home_controller_decorator.rb

Which will load this file: https://github.com/suryart/spree_active_sale/blob/master/app/views/spree/home/index.html.erb

index view file is suppose to load all sale events from the database, now the events will only be visible when they have sale_images, which can be again uploaded by Admin in Active Sale Events area under a particular Active Sale. 

So, there will be no issue once you add this plugin in a vanilla app. However if developer already has home_controller.rb in controllers and have index method and its template in their application, rails is going to honor the application's level home_controller and will not consider plugin's methods. And, that's where developer might face issues.

Though, I will create a rake task to copy view and assets from plugin to the user's/developer's application directory. So that, developer can modify the code according to their requirement like: changing template, look of the count down timer, UI, UX etc etc.
